"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
from pathlib import Path
from django.contrib.messages import constants as messages_constants

# initialize environnement variable
env = environ.Env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env('/private/.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = env.str('SECRET_KEY', default='your-secret-key')
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# SECURITY PRODUCTION
if not DEBUG:
    # HTTPS settings
    SESSION_COOKIE_SECURE = True  # Force les cookies de session à être transmis uniquement via HTTPS
    CSRF_COOKIE_SECURE = True     # Force les cookies CSRF à être transmis uniquement via HTTPS
    SECURE_SSL_REDIRECT = True    # Redirige automatiquement toutes les requêtes HTTP vers HTTPS
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Détecte HTTPS derrière un proxy
    # HSTS settings (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000        # Durée (1 an) pendant laquelle le navigateur doit utiliser HTTPS uniquement
    SECURE_HSTS_PRELOAD = True            # Permet l'inclusion dans la liste de préchargement HSTS des navigateurs
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True # Applique la politique HSTS à tous les sous-domaines
    # Allauth settings with 1 proxy trusted by NGINX
    ALLAUTH_TRUSTED_PROXY_COUNT = 1                # default=0
    ALLAUTH_TRUSTED_CLIENT_IP_HEADER = "X-Real-IP" # default=None, NGINX="X-Real-IP", Cloudflare="CF-Connecting-IP"

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    # application declaration
    'accounts',
    'core',
    'nutrition'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Add the middleware for allauth
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # collectstatic for nginx
STATICFILES_DIRS = [
    BASE_DIR / 'static', # dev: css, js, bootstrap
]
# users upload
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'mediafiles'
# custom user definition
AUTH_USER_MODEL = "accounts.CustomUser"
# django message configuration: Associate ERROR to danger color type
MESSAGE_TAGS = {
    messages_constants.ERROR: "danger",
}
# email configuration: output to django development console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Allauth settings
ACCOUNT_LOGIN_METHODS = ("username", "email")
# désactive vérification par email par défaut
ACCOUNT_EMAIL_VERIFICATION = "optional"
# Cas d'utilisation d'un formulaire avec champs personalisés
# ACCOUNT_FORMS = {'signup': 'accounts.forms.CustomSignupForm'}

